/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Martijn Vaes (https://sketchfab.com/MartijnVaes)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dae-villages-the-broken-hearts-club-d1f43cf04a6f4eea92398f5f5d298359
Title: DAE Villages | The broken hearts club
*/

import React, { useRef, useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame, useThree } from '@react-three/fiber';
import { a } from '@react-spring/three';

import islandScene from '../assets/3d/island.glb';

const Island = (props) => {

  const islandRef = useRef();
  const { nodes, materials } = useGLTF(
    islandScene
  );
  return (
    <a.group ref={islandRef} {...props}>
      <group position={[-52.297, 0.09, -27.04]}>
        <mesh
          geometry={nodes.polySurface211_lambert5_0.geometry}
          material={materials.lambert5}
        />
        <mesh
          geometry={nodes.polySurface211_lambert6_0.geometry}
          material={materials.lambert6}
        />
        <mesh
          geometry={nodes.polySurface211_lambert7_0.geometry}
          material={materials.lambert7}
        />
        <mesh
          geometry={nodes.polySurface211_lambert3_0.geometry}
          material={materials.lambert3}
        />
      </group>
    </a.group>
  );
}

export default Island;